### PR TITLE
fix: displaying status and output for deploy events

### LINKED ISSUE #363: bug(workflow): deploy run output not being shown in the workflow
when we `Deploy` the workflow, the output of the deploy run is not showing in the workflow cells or in the sidebar.

### PR DESCRIPTION
**Pull request by boandriy**
displaying status and output for deploy events, removed deploy events from Toasts

fixes #363

### CODE REVIEW

File: src/features/deploy/state/deployState.ts [hunk 1]
```diff
@@ -25,13 +25,18 @@ export function selectDeployStatus(qriRef: QriRef): (state: RootState) => Deploy
   return (state: RootState): DeployStatus => (state.deploy.status[`${qriRef.username}/${qriRef.name}`])
 }
 
+export const selectDeployRunId = (state: RootState): string => {
+  return state.deploy.deployRunId
+}
 
 export interface DeployState {
   status: Record<string,DeployStatus>
+  deployRunId: string
```
Comment (b5) [inline src/features/deploy/state/deployState.ts]: field with `deploy` prefix on a a structure called `deploy` stutters use `runID` instead, and add a comment:

```ts
export interface DeployState {
  status: Record<string, DeployStatus>
  runID: string  // runID of deploying dataset, empty string means no deploying run
}
```

File: src/features/workflow/WorkflowPage.tsx [hunk 2]
```diff
@@ -21,7 +22,8 @@ const WorkflowPage: React.FC<WorkflowPageProps> = ({ qriRef }) => {
   const dispatch = useDispatch()
   let dataset = useSelector(selectWorkflowDataset)
   const latestDryRunId = useSelector(selectLatestDryRunId)
-  const latestRun = useSelector(selectRun(latestDryRunId))
+  const latestDeployId = useSelector(selectDeployRunId)
+  const latestRun = useSelector(selectRun(latestDryRunId ? latestDryRunId : latestDeployId))
```
Comment (b5) [inline src/features/workflow/WorkflowPage.tsx]: rather than defining separate selectors & combining them in this way, we should add a new selector in `workflowState.ts` that pulls from both the deploy _and_ workflow sections of the state tree, combining the `selectDeployRunID` and `selectLatestDryRunID` selectors:

```ts
// workflowState.ts

export const selectLatestRunId = (state: RootState): string => {
  if (state.deploy.runID !== '') { 
    return state.deploy.runID
  }
  if (state.workflow.lastDryRunID) {
    return state.workflow.lastDryRunID
  }
  return ''
}
```

bonus points if you make `workflow.lastDryRunID` non-optional and default to the empty string as "no latest run", as we're doing with `deploy.runID`, then the above can be refactored to just return `state.workflow.lastDryRunID` instead of using the second if clause

File: src/features/workflow/state/workflowState.ts [hunk 3]
```diff
@@ -42,6 +44,13 @@ export const selectLatestDryRunId = (state: RootState): string => {
   return ''
 }
 
+export const selectLatestDryRunDeployId = (state: RootState): string => {
```
Comment (b5) [inline src/features/workflow/state/workflowState.ts]: should modify this function name to match it's priority, how about `selectLatestDeployOrDryRunId`?

File: src/features/workflow/state/workflowState.ts [hunk 4]
```diff
@@ -92,7 +101,7 @@ export interface WorkflowState {
   // cell output was cleared
   clearedOutputCells: boolean[]
   isDirty: boolean
-  lastDryRunID?: string
+  lastDryRunID: string
```
Comment (b5) [inline src/features/workflow/state/workflowState.ts:104]: ❤️ whenever a field becomes non-optional

File: src/features/workflow/state/workflowActions.ts [hunk 5]
```diff
@@ -18,7 +18,8 @@ import {
   WORKFLOW_MOVE_TRANSFORM_STEP_UP,
   WORKFLOW_MOVE_TRANSFORM_STEP_DOWN,
   WORKFLOW_UNDO_CHANGES,
-  WORKFLOW_CLEAR_TRANSFORM_STEP_OUTPUT
+  WORKFLOW_RESET_DRY_RUN_ID,
+  WORKFLOW_CLEAR_TRANSFORM_STEP_OUTPUT, WORKFLOW_RESET_EDITED_CLEARED_CELLS
```
Comment (b5) [inline src/features/workflow/state/workflowActions.ts]: either go one import per line, or all imports on one line, avoid mixing.

**Review by b5 — APPROVED** [review]
a few nits, then looks good to me!
