### PR TITLE
fix: fixed UI of deploy modal to fit all content

### LINKED ISSUE #370: Long content in deploy modal is hidden
The deploy modal is fixed height because it contains several screens in the same modal.  The warning gets bumped due to the content above.

I think we probably need to keep it fixed height but control the heights of the rest of the content to make sure there's always an empty spot for warnings.

image

### PR DESCRIPTION
**Pull request by boandriy**
fixed UI of deploy modal to fit all content
 
 fixes #370

### CODE REVIEW

File: src/features/workflow/modal/DeployModal.tsx [hunk 1]
```diff
@@ -178,12 +179,13 @@ const DeployModal: React.FC = () => {
...
+  }
+
   return (
-    <div style={{ width: 440, height: 440 }}>
-      <div className={classNames('absolute w-full h-full bg-white p-8 transition-all duration-300 bg-white p-8 text-left text-black flex flex-col z-10', {
-        'left-0': !deploying,
-        '-left-full': deploying
-      })}>
+    <div style={{ width: 440 }}>
+      {!isDeploying() && <div className={'w-full h-full bg-white p-8 transition-all duration-300 bg-white p-8 text-left text-black flex flex-col z-10'}>
```
Comment (ramfox) [inline src/features/workflow/modal/DeployModal.tsx]: it looks like we are losing a transition moment here with this change.

If you look at the deploy screens in `master`, the screen swipes to the left when you click "run deploy", on this branch we don't have a transition.

**Review by ramfox — CHANGES_REQUESTED** [review]
looks like the change makes us lose a transition

**Review by b5 — APPROVED** [review]
