### PR TITLE
fix: fix cell spacing bug

### LINKED ISSUE #421: Cell spacing
image

Short cells have unnecessary spacing due to the hidden cell menu.  The cell menu should be styled to overflow the container so only the cell editor affects the height.

### PR DESCRIPTION
**Pull request by chriswhong**
Style tweaks to keep cell spacing consistent.  (Sticky cell controls were causing excess space under short/new cells) Closes #421

### CODE REVIEW

File: src/features/workflow/WorkflowCell.tsx [hunk 1]
```diff
@@ -91,43 +91,42 @@ const WorkflowCell: React.FC<WorkflowCellProps> = ({
...
+            width: 'calc(100% - 225px)'
+          }}
+        >
+          {/* ^^ this wrapping div allows us to use two different borders.  Active cell shows both, allowing for a thicker border without causing content to shift*/}
           <div
-            className={classNames(`border rounded-lg ${active && borderStyles}`, {
-              'border-transparent': !active
+            className={classNames(`rounded-lg overflow-hidden flex-grow border box-content ${borderStyles}`, {
+              'border-transparent hover:border-qrigray-200': !active && (noColorStatus)
             })}
```
Comment (b5) [inline src/features/workflow/WorkflowCell.tsx]: this can be rewritten to drop the template string (which transpiles to a function call IIRC):

```ts
className={classNames(
  'rounded-lg overflow-hidden flex-grow border box-content',
  borderStyles,
  'border-transparent hover:border-qrigray-200': !active && (noColorStatus)
)}
```

**Review by b5 — APPROVED** [review]
one nit then LGTM
