### PR TITLE
fix: readme now only expands if content exceeds container

### LINKED ISSUE #571: Don't show "Read More" on readmes unless there is more to see
"Read more" still shows when the readme content is short.  (See http://localhost:3000/xristosk/nyc_daily_inmates_in_custody)

When clicked, the div shrinks to fit the content.
Let's make it so that "Read more" only shows if the content is actually larger than the initial div

### PR DESCRIPTION
**Pull request by boandriy**
readme now only expends if content exceeds container

fixes #571

### CODE REVIEW

**Review by chriswhong — APPROVED** [review]
Added a transition to the bottom of the overflowing container so the text doesn't get cut off so abruptly.

File: src/features/dsPreview/DatasetPreviewPage.tsx [hunk 1]
```diff
@@ -35,9 +35,24 @@ const DatasetPreviewPage: React.FC<DatasetPreviewPageProps> = ({
...
+  useEffect(() => {
+    if (!isNaN(readmeContainerHeight)) {
+      setMinReadmeHeight(readmeContainerHeight - 42)// removing padding here
+    }
+  }, [ readmeContainerHeight ])
+
+  useEffect(() => {
+    const readmeComponent = document.getElementsByClassName('markdown-body')[0]
+    if (readmeComponent) {
+      setReadmeHeight(readmeComponent.clientHeight + 64) // adding pudding and see more button dimensions
```
Comment (ramfox) [inline src/features/dsPreview/DatasetPreviewPage.tsx]: spelling in comment:

"pudding" => "padding"

**Review by ramfox — APPROVED** [review]
one spelling mistake in a comment that should be fixed, otherwise LGTM!
