### PR TITLE
fix: Display username and dataset name in toast as link to a ds preview

### LINKED ISSUE #261: Toast identifies the dataset that is running
We should be able to see the `username/name`, and perhaps the run number when a toast shows up.  On success or failure, clicking the toast (or a link in the toast) should go to the run log.

### PR DESCRIPTION
**Pull request by boandriy**
Display username and dataset name in toast as link to a ds preview
Edited the collection state to include runs version info object

image

Fixes #261

### CODE REVIEW

File: src/features/toast/Toast.tsx [hunk 1]
```diff
@@ -23,6 +25,10 @@ const Toast: React.FC<ToastProps> = ({ message, type, id }) => {
           'text-qrigreen': type === 'succeeded',
           'text-qrired-700': type === 'failed',
         })}>{message}</div>
+        <Link to={'/ds/'+name}
+              className='text-qrinavy w-56 whitespace-nowrap overflow-hidden block text-sm overflow-ellipsis'>
+          {name}
+        </Link>
         <div className='text-xs'>{id}</div>
```
Comment (ramfox) [inline src/features/toast/Toast.tsx]: we should remove the id now that we have the dataset reference hooked up correctly!

File: src/features/toast/Toast.tsx [hunk 2]
```diff
@@ -2,15 +2,17 @@ import React from 'react'
 import classNames from 'classnames'
 import RunStatusIcon from '../run/RunStatusIcon'
 import IconButton from '../../chrome/IconButton'
+import { Link } from "react-router-dom";
 
 interface ToastProps {
   message: string
+  name: string
```
Comment (ramfox) [inline src/features/toast/Toast.tsx]: `name` should be renamed to `ref`. 

In Qri, the `name` refers to just the name of the dataset. In this case, we are sending the `username/name` combination, which we call the "dataset reference", usually shortened to `ref`.

(Technically, the dataset reference can be as short as the `username/name` combo or as long as `username/name@initID/network/path`, etc, but is usually just the `username/name`)

File: src/features/toast/ToastRenderer.tsx [hunk 3]
```diff
@@ -1,41 +1,85 @@
...
+        const initialResponse = await fetch(`${API_BASE_URL}/collection/get`, {
+          method: 'POST',
+          body: JSON.stringify({initID: initId})
+        })
+        const response:VersionInfo = await initialResponse.json().then(r => r.data)
+        if(response){
+          setCollections([...collections, response])
+        }
+      }
+    })
```
Comment (ramfox) [inline src/features/toast/ToastRenderer.tsx]: usually when we see fetching happening in the component along the use of `useState`, it usually means we are missing something in redux. I proposed a large-ish refactor here that changes the way we think of the `state.collection.collection` & uses it as a place to store version infos, rather than the place that tells us what collections to show on the "My Collections" page. It would also mean a bunch of changes to this `ToastRenderer` component: https://github.com/qri-io/frontend/issues/261#issuecomment-928447901

LMK if you have any questions!

**Review by ramfox — CHANGES_REQUESTED** [review]
I think we are missing some things in our current redux store that is making the patterns we have in the `ToastRenderer` component not as clean as we would like them to be. Take a look at my comment here https://github.com/qri-io/frontend/pull/347#discussion_r717117719 and let me know if you have any questions

File: src/features/collection/state/collectionState.ts [hunk 4]
```diff
@@ -31,6 +32,9 @@ export const selectCollection = (state: RootState): VersionInfo[] => {
   })
 }
 
+export const selectVersionInfo = ( initId: string): (state: RootState) => VersionInfo =>
```
Comment (ramfox) [inline src/features/collection/state/collectionState.ts:35]: `( initId: string)` => `(initId: string)`

File: src/features/collection/state/collectionState.ts [hunk 5]
```diff
@@ -84,6 +94,14 @@ export const collectionReducer = createReducer(initialState, {
...
     state.runningLoading = false
   },
+  'API_VERSIONINFO_REQUEST' : (state, action) => {
+    state.pendingIDs.push(action[CALL_API].body.initID)
+  },
+  'API_VERSIONINFO_SUCCESS':(state, action) => {
+    const versionInfo: VersionInfo = action.payload.data;
+    state.pendingIDs = state.pendingIDs.filter(id => id !== versionInfo.initID)
+    state.collection[versionInfo.initID] = newVersionInfo(versionInfo)
+  },
```
Comment (ramfox) [inline src/features/collection/state/collectionState.ts:108]: should add a failure case here to remove the initID from the `pending` list. If this causes an infinite loop we should talk over how to fix it.

File: src/features/toast/Toast.tsx [hunk 6]
```diff
@@ -2,15 +2,27 @@ import React from 'react'
...
+import { VersionInfo } from "../../qri/versionInfo";
 
 interface ToastProps {
   message: string
+  initID:string
   type: 'running' | 'succeeded' | 'failed'
-  id: string
 }
 
+const getRef = (vi: VersionInfo | undefined) => {
```
Comment (ramfox) [inline src/features/toast/Toast.tsx]: nice, we already have something like this:
https://github.com/qri-io/frontend/blob/6726bc5c4f653ee66eb7dd3f362fa640e46115c3/src/qri/versionInfo.ts#L94-L96

We should modify it so that if there is no username or name then we return an empty string (rather than '/')

File: src/features/toast/ToastRenderer.tsx [hunk 7]
```diff
@@ -1,41 +1,49 @@
...
+  const initIDs = runs.map((r: Run) => r.initID)
 
   // artifically delay the update to 'success'
   const SUCCESS_START_DELAY = 0
 
   // after 'success', close the toast 4 seconds later
   const SUCCESS_CLOSE_DELAY = 4000
 
+  useEffect(() => {
+    initIDs.forEach((initId) => {
```
Comment (ramfox) [inline src/features/toast/ToastRenderer.tsx]: we should be adding type to as much as we can:

`initIDs.forEach((initID: string) => {`

File: src/features/collection/state/collectionActions.ts [hunk 8]
```diff
@@ -15,6 +16,18 @@ export function loadCollection() {
...
 }
 
+export function loadVersionInfo(initID: string) {
+  return async (dispatch, getState: () => RootState) => {
+    const state = getState();
+    if(state.collection.collection[initID]){
+      return state.collection.collection[initID]
+    }else if(!state.collection.pendingIDs.includes(initID)){
+      return dispatch(fetchVersionInfo(initID))
+    }else return
```
Comment (ramfox) [inline src/features/collection/state/collectionActions.ts]: some linting errors here:

```
    if (state.collection.collection[initID]) {
      return state.collection.collection[initID]
    } else if (!state.collection.pendingIDs.includes(initID)) {
      return dispatch(fetchVersionInfo(initID))
    } else return
```

**Review by ramfox — CHANGES_REQUESTED** [review]
Hey hey!

Looks great!!!

I have a view renaming/linting comments.

I'm getting these `eslint` warning when I run `yarn start`

```
src/features/app/modal/Modal.tsx
  Line 1:49:  'useState' is defined but never used  @typescript-eslint/no-unused-vars

src/features/commits/CommitSummaryHeader.tsx
  Line 14:19:  'path' is assigned a value but never used  @typescript-eslint/no-unused-vars

src/features/dataset/DatasetRoutes.tsx
  Line 35:5:  React Hook useEffect has a missing dependency: 'qriRef'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/features/dsPreview/state/dsPreviewActions.ts
  Line 1:18:  'refStringFromQriRef' is defined but never used  @typescript-eslint/no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

I think these may have been fixed in previous prs tho, maybe they will go away after rebasing?

File: src/features/collection/state/collectionState.ts (hunk 5 above)
Comment (boandriy) [reply src/features/collection/state/collectionState.ts:108]: @ramfox , it causes infinite loop.

Comment (ramfox) [reply src/features/collection/state/collectionState.ts:108]: okay fab. After looking into this more, I think we have some bigger structural issues to deal with that will help fix this problem, so we should just leave it alone for now and move on.

File: src/features/collection/state/collectionActions.ts (hunk 8 above)
Comment (b5) [reply src/features/collection/state/collectionActions.ts]: if statements are still missing spaces.

File: src/features/collection/state/collectionState.ts (hunk 4 above)
Comment (b5) [reply src/features/collection/state/collectionState.ts:35]: still not resolved. check spacing around leading parenthesis

File: src/features/collection/state/collectionState.ts [hunk 9]
```diff
@@ -39,25 +43,31 @@ export interface CollectionState {
   // running contains the ids of the currently running workflows in reverse chronological
   // order based on latestRunTime
   running: string[]
+  listedIDs: string[]
+  pendingIDs: string[]
```
Comment (b5) [inline src/features/collection/state/collectionState.ts]: I'd appreciate comments on what these two lists are doing, similar to the running field above:

```ts
// ids of datasets in the current user's collection
listedIDs: Set<string>
// ids of datasets not (or not yet) in the user's collection
pendingIDs: string[]
```

File: src/features/collection/state/collectionState.ts [hunk 10]
```diff
@@ -39,25 +43,31 @@ export interface CollectionState {
...
   'API_COLLECTION_REQUEST': (state, action) => {
-    state.collection = {}
+    state.listedIDs = []
     state.collectionLoading = true
   },
   'API_COLLECTION_SUCCESS': (state, action) => {
     action.payload.data.forEach((d: VersionInfo) => {
       state.collection[d.initID] = d
+      state.listedIDs.push(d.initID)
     })
```
Comment (b5) [inline src/features/collection/state/collectionState.ts]: this leaves open the chance of repeating IDs in the `listedIDs` array. What we need is a set union between current and new values, and the easiest way to do that is to make the `listedIDs` field a `Set<string>` type. You'll need to use `.add` instead of `.push`

```ts
 action.payload.data.forEach((d: VersionInfo) => {
      state.collection[d.initID] = d
      state.listedIDs.add(d.initID)
  })
```

File: src/features/collection/state/collectionState.ts [hunk 11]
```diff
@@ -39,25 +43,31 @@ export interface CollectionState {
...
+  pendingIDs: string[]
   collectionLoading: boolean
   runningLoading: boolean
+
 }
 
 const initialState: CollectionState = {
   collection: {},
   running: [],
+  listedIDs: [],
```
Comment (b5) [inline src/features/collection/state/collectionState.ts]:
```suggestion
  listedIDs: new Set(),
```

File: src/features/collection/state/collectionState.ts [hunk 12]
```diff
@@ -39,25 +43,31 @@ export interface CollectionState {
...
+  pendingIDs: [],
   collectionLoading: true,
   runningLoading: true
 }
 
 export const collectionReducer = createReducer(initialState, {
   'API_COLLECTION_REQUEST': (state, action) => {
-    state.collection = {}
+    state.listedIDs = []
```
Comment (b5) [inline src/features/collection/state/collectionState.ts]: `state.listedIDs = new Set()`

**Review by b5 — CHANGES_REQUESTED** [review]
coming along nicely! A few things to clean up

File: src/features/collection/state/collectionActions.ts (hunk 8 above)
Comment (b5) [reply src/features/collection/state/collectionActions.ts]: _still_ missing. Maybe the wrong rule is writing on save in your IDE?

Comment (boandriy) [reply src/features/collection/state/collectionActions.ts]: @b5 ,  sorry.. fixed ^

**Review by ramfox — APPROVED** [review]
LGTM! Great work!
